### PR TITLE
🎉hieroglyphs.top

### PR DESCRIPTION
**Pull request by imjiaoyuan**
之前搞忘记了，现已添加

### CODE REVIEW

**Review by YuZhangWang — COMMENTED** [review]
Why did you close Pr, and why did you remove the Fork repository?How else can I merge Pr if the Fork repository is removed?
After you perform a Pr operation, the original repository should not delete the repository you Forked until it fails to merge your Pr, as well as you should not close your Pr!

**Review by YuZhangWang — COMMENTED** [review]
Why would you want to add your friend link in a category that indicates an invalid link? 
You should choose a category that belongs to you and add it correctly!

**Comment by YuZhangWang** [comment]
Why do you change the correct "[" symbol to "{", this will lead to mismatched brackets and syntax problems, I suggest you take a good look at the documentation, and the brackets in this file are not matched!

**Review by YuZhangWang — COMMENTED** [review]
Why do you change the correct "[" symbol to "{", this will lead to mismatched brackets and syntax problems, I suggest you take a good look at the documentation, and the brackets in this file are not matched!

**Comment by YuZhangWang** [comment]
I feel speechless, this repository doesn't need you next Pr, your Pr submission is a mess, I've modified the json file and now your friend link has been added to my site .

**Comment by imjiaoyuan** [comment]
Sorry, I didn't look carefully, my question.

**Comment by YuZhangWang** [comment]
> Sorry, I didn't look carefully, my question.

总之就是，你的Pr目前是一团糟
1.你把提交的Pr给关闭了，这导致无法合并
2.你删除了Fork的仓库，这也是导致Pr关闭的原因，以后提交Pr，不要删除Fork的仓库，这点很重要
3.你把自己添加到了错误的类别中，你添加的那一类属于失联的友链，也就是无效友链，你应该在上面几个类别中选择你的类别
4.在你第1次提交的时候，你就把原来的括号删除了一个，应该是"}"这个括号，这样导致了外部几层括号不匹配了，你意识到了这个问题，在你第2次提交的时候，你把原本外面一层的"]"改成了“}”,内部是匹配上了，但是外部往上两层却少了一个“]”，这会导致远程json文件拉取，直接失效

我在代码审查中，把具体问题标注了下，这次我帮你在文件中进行了添加，你现在可以直接在我的博客友链中，看到你的链接了，注意这是随机显示的

图片

但是下一次，如果你需要更改信息，那么还是需要你自己进行Pr提交，希望下次可以使用正确

Finally，代码规范方面还是再多注意一下，好的代码不仅要会写，能跑，还要写的优美，整体美观可读，尤其是细节要多注意

**Pull request closed without merging**
